### ISSUE TITLE
Methylation coverage question/problem

### ISSUE THREAD

**Issue by mvolar** [FelixKrueger/Bismark#521] opened 2022-09-01 11:16 UTC
Hello everyone,

I love the tool personally and never had any issue with it, up until now.  When inspecting the .cov file I see that my methylation percentage (and coverage to some degree) do not correspond to what I am observing whel looking at the raw .deduplicated.bam file.

The coverage file looks like this

![image](https://user-images.githubusercontent.com/89461052/187900116-0d7ba1c8-f031-4cba-88d8-5c3bfbf3edd3.png)

While when looking at those same bases in Geneious (base 481, last line in the bedgraph)

![image](https://user-images.githubusercontent.com/89461052/187901053-56344f95-f9f6-4f30-a5d2-b66d7f6f7e30.png)

It is obvious that the number of methylated bases is at least 2 (2 G-s at the middle of the picture) and the coverage is at least 35. Could you give me a guide why is that so and what can I do to better understand the reasoning behind it?

**Comment by FelixKrueger** [comment] 2022-09-01 14:13
I'm currently traveling but will be back on the 3rd, will aim to respond then. Apologies for the delay

**Comment by FelixKrueger** [comment] 2022-09-04 06:21
I can't say with certainty from this screenshot, but since the truncated read IDs appear to occur in pairs (also sequences always start and end at the same position), am I correct in assuming that we are looking at paired-end data?

If this is paired-end data, the most likely explanation is that the read-overlap detection (and removal) has only taken into account one methylation for that position, and discarded the second one as it is merely a PCR duplicate of the call in Read 1. You should be able to test this theory by specifying `--include_overlap` (or similar) during the methylation extraction and coverage file generation, where you would then indeed expect a methylated count of 2 (I am not suggesting you should be doing that going forward, but you could test this hypothesis). Let me know if this could explain it?

**Comment by mvolar** [comment] 2022-09-28 11:42
Sorry for the long delay, I seemed to have missed the response notification. It looks like it is the fwd-rev overlapping that is missing, thanks for the assist.

**Comment by FelixKrueger** [comment] 2022-09-28 12:35
Excellent, glad we found a solution.

**Closed by FelixKrueger** 2022-09-28 12:35 UTC
